import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, "antialiased bg-gray-50 text-gray-900")}>
        <header className="border-b p-4 bg-white shadow-sm">
          <div className="max-w-5xl mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold text-green-700">Sabay.ph</h1>
            <nav className="space-x-4 text-sm font-medium">
              <a href="/dashboard">Dashboard</a>
              <a href="/rides">Rides</a>
              <a href="/routes">Routes</a>
            </nav>
          </div>
        </header>
        <main className="max-w-5xl mx-auto py-6">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
